import type { ImageSourcePropType } from 'react-native';

/**
 * Ảnh sản phẩm mẫu là bundled asset local trong `src/assets/mock-shopping/`
 * (Pexels free license — được dùng thương mại, không cần credit). Hoàn toàn
 * offline, không gọi network, deterministic khi test — cùng tinh thần với
 * `momentsMockPosts.ts`.
 */

export type ShoppingCategory = {
  id: string;
  label: string;
  icon: string;
};

export type ShoppingSeller = {
  id: string;
  name: string;
  verified: boolean;
  province?: string;
};

export type ShoppingProduct = {
  id: string;
  title: string;
  shop: string;
  category: string;
  price: string;
  originalPrice?: string;
  badge?: string;
  rating: number;
  soldCount: number;
  sold: string;
  delivery: string;
  accent: string;
  icon: string;
  tags: string[];
  description?: string;
  seller: ShoppingSeller;
  /**
   * Bundled offline mock photo (`require()` result — `number` under RN's
   * asset pipeline). Optional: `accent`/`icon` stay the loading/fallback
   * visual (accent-tinted backdrop + glyph) while the image decodes or if
   * a product has none, same intent as `momentsMockPosts.ts`.
   */
  image?: ImageSourcePropType;
};

export type ShoppingStore = {
  id: string;
  name: string;
  category: string;
  distance: string;
  eta: string;
  rating: number;
  icon: string;
  accent: string;
};

export const shoppingCategories: ShoppingCategory[] = [
  { id: 'all', label: 'Tất cả', icon: 'apps' },
  { id: 'grocery', label: 'Tạp hóa', icon: 'local-grocery-store' },
  { id: 'food', label: 'Đồ ăn', icon: 'restaurant' },
  { id: 'electronics', label: 'Điện tử', icon: 'phone-iphone' },
  { id: 'home', label: 'Nhà cửa', icon: 'home' },
  { id: 'beauty', label: 'Làm đẹp', icon: 'spa' },
];

export const shoppingSortChips = ['Được mua nhiều nhất', 'Giá thấp nhất'] as const;
export const shoppingAttributeChips = ['Organic', 'Chứng nhận', 'Đã xác minh'] as const;

export const shoppingProducts: ShoppingProduct[] = [
  {
    id: 'p1',
    title: 'Combo rau củ tươi Đà Lạt',
    shop: 'Koola Fresh Market',
    category: 'grocery',
    price: '89.000đ',
    originalPrice: '119.000đ',
    badge: 'Giao 2h',
    rating: 4.8,
    soldCount: 1200,
    sold: '1.2k',
    delivery: 'Miễn phí gần bạn',
    accent: '#10B981',
    icon: 'eco',
    tags: ['Organic', 'Không đường', 'Chính hãng'],
    description: 'Rau củ tươi hái mỗi sáng tại Đà Lạt, giao trong ngày. Combo 3-4 loại theo mùa, kèm hướng dẫn bảo quản.',
    seller: { id: 'seller-fresh', name: 'Koola Fresh Market', verified: true, province: 'Đà Lạt' },
    image: require('../../assets/mock-shopping/vegetables.jpg'),
  },
  {
    id: 'p2',
    title: 'Cơm gà sốt tiêu xanh',
    shop: 'Bếp Nhà Koola',
    category: 'food',
    price: '45.000đ',
    badge: 'Bán chạy',
    rating: 4.7,
    soldCount: 860,
    sold: '860',
    delivery: '25 phút',
    accent: '#F97316',
    icon: 'restaurant',
    tags: ['Không đường', 'Chính hãng'],
    description: 'Cơm gà ta sốt tiêu xanh, ăn kèm rau trộn và canh. Bếp nấu theo đơn, giao nóng trong 25 phút.',
    seller: { id: 'seller-bep', name: 'Bếp Nhà Koola', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/chicken-rice.jpg'),
  },
  {
    id: 'p3',
    title: 'Tai nghe Bluetooth Mini',
    shop: 'Tech Corner',
    category: 'electronics',
    price: '249.000đ',
    originalPrice: '319.000đ',
    badge: '-22%',
    rating: 4.6,
    soldCount: 540,
    sold: '540',
    delivery: 'Hôm nay',
    accent: '#2563EB',
    icon: 'headphones',
    tags: ['Chính hãng', 'Chứng nhận'],
    description: 'Tai nghe nhét tai Bluetooth 5.3, pin 6h, kèm case sạc. Đổi mới 7 ngày nếu lỗi kỹ thuật.',
    seller: { id: 'seller-tech', name: 'Tech Corner', verified: false, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/earbuds.jpg'),
  },
  {
    id: 'p4',
    title: 'Bộ lau nhà gấp gọn',
    shop: 'Nhà Xinh Store',
    category: 'home',
    price: '159.000đ',
    badge: 'Hot',
    rating: 4.5,
    soldCount: 430,
    sold: '430',
    delivery: 'Giao trong ngày',
    accent: '#14B8A6',
    icon: 'home',
    tags: ['Đã xác minh', 'Chính hãng', 'Chứng nhận'],
    description: 'Bộ lau nhà gấp gọn, đầu lau xoay 360°, cán inox. Gọn khi cất, bền khi dùng.',
    seller: { id: 'seller-nhaxinh', name: 'Nhà Xinh Store', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/mop.jpg'),
  },
  {
    id: 'p5',
    title: 'Sữa rửa mặt dịu nhẹ',
    shop: 'Beauty Lab',
    category: 'beauty',
    price: '129.000đ',
    originalPrice: '169.000đ',
    badge: 'Deal',
    rating: 4.9,
    soldCount: 2100,
    sold: '2.1k',
    delivery: 'Freeship',
    accent: '#EC4899',
    icon: 'spa',
    tags: ['Chính hãng'],
    description: 'Sữa rửa mặt pH 5.5, không cồn, cho da nhạy cảm. Dung tích 120ml, dùng ~2 tháng.',
    seller: { id: 'seller-beauty', name: 'Beauty Lab', verified: true, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/skincare.jpg'),
  },
  {
    id: 'p6',
    title: 'Gạo thơm ST25 túi 5kg',
    shop: 'Chợ Việt Online',
    category: 'grocery',
    price: '168.000đ',
    badge: 'Hàng mới',
    rating: 4.8,
    soldCount: 980,
    sold: '980',
    delivery: 'Giao 4h',
    accent: '#F59E0B',
    icon: 'rice-bowl',
    tags: ['Organic', 'Đã xác minh'],
    description: 'Gạo ST25 chính vụ, dẻo thơm, đóng túi hút chân không 5kg. Giao 4h nội thành.',
    seller: { id: 'seller-choviet', name: 'Chợ Việt Online', verified: false, province: 'Cần Thơ' },
    image: require('../../assets/mock-shopping/rice.jpg'),
  },
  // ── seller-fresh 7 thêm (p7-p13) ─────────────────────────────────
  {
    id: 'p7',
    title: 'Dâu tây Đà Lạt hộp 500g',
    shop: 'Koola Fresh Market',
    category: 'grocery',
    price: '79.000đ',
    originalPrice: '99.000đ',
    badge: 'Tươi mỗi ngày',
    rating: 4.9,
    soldCount: 1850,
    sold: '1.8k',
    delivery: 'Giao 2h',
    accent: '#10B981',
    icon: 'eco',
    tags: ['Organic', 'Đã xác minh'],
    description: 'Dâu tây giống Nhật trồng tại Đà Lạt, hái sáng giao chiều. Hộp 500g, ngọt thanh, mọng nước.',
    seller: { id: 'seller-fresh', name: 'Koola Fresh Market', verified: true, province: 'Đà Lạt' },
    image: require('../../assets/mock-shopping/chicken-rice.jpg'),
  },
  {
    id: 'p8',
    title: 'Bơ sáp 034 size lớn 1kg',
    shop: 'Koola Fresh Market',
    category: 'grocery',
    price: '69.000đ',
    badge: 'Bán chạy',
    rating: 4.7,
    soldCount: 1420,
    sold: '1.4k',
    delivery: 'Miễn phí gần bạn',
    accent: '#10B981',
    icon: 'eco',
    tags: ['Organic', 'Chính hãng'],
    description: 'Bơ 034 cơm vàng dẻo, hạt nhỏ. 1kg khoảng 2-3 trái, chín tự nhiên không thuốc.',
    seller: { id: 'seller-fresh', name: 'Koola Fresh Market', verified: true, province: 'Đà Lạt' },
    image: require('../../assets/mock-shopping/earbuds.jpg'),
  },
  {
    id: 'p9',
    title: 'Salad mix hữu cơ 300g',
    shop: 'Koola Fresh Market',
    category: 'grocery',
    price: '39.000đ',
    rating: 4.6,
    soldCount: 980,
    sold: '980',
    delivery: 'Giao 2h',
    accent: '#10B981',
    icon: 'eco',
    tags: ['Organic', 'Không đường'],
    description: 'Rau salad mix 5 loại hữu cơ, đã rửa sạch, đóng hộp 300g. Ăn liền hoặc trộn sốt.',
    seller: { id: 'seller-fresh', name: 'Koola Fresh Market', verified: true, province: 'Đà Lạt' },
    image: require('../../assets/mock-shopping/mop.jpg'),
  },
  {
    id: 'p10',
    title: 'Nấm đùi gà tươi 400g',
    shop: 'Koola Fresh Market',
    category: 'grocery',
    price: '55.000đ',
    badge: 'Hàng mới',
    rating: 4.5,
    soldCount: 620,
    sold: '620',
    delivery: 'Giao trong ngày',
    accent: '#10B981',
    icon: 'eco',
    tags: ['Organic', 'Chứng nhận'],
    description: 'Nấm đùi gà trồng trong phòng lạnh, giòn ngọt, không chất bảo quản. Gói 400g.',
    seller: { id: 'seller-fresh', name: 'Koola Fresh Market', verified: true, province: 'Đà Lạt' },
    image: require('../../assets/mock-shopping/skincare.jpg'),
  },
  {
    id: 'p11',
    title: 'Khoai lang mật Tà Nung 2kg',
    shop: 'Koola Fresh Market',
    category: 'grocery',
    price: '59.000đ',
    originalPrice: '79.000đ',
    badge: '-25%',
    rating: 4.8,
    soldCount: 2100,
    sold: '2.1k',
    delivery: 'Giao 4h',
    accent: '#10B981',
    icon: 'eco',
    tags: ['Organic', 'Đã xác minh', 'Chính hãng'],
    description: 'Khoai lang mật Tà Nung nướng chảy mật, dẻo ngọt. Túi 2kg, củ vừa đều.',
    seller: { id: 'seller-fresh', name: 'Koola Fresh Market', verified: true, province: 'Đà Lạt' },
    image: require('../../assets/mock-shopping/rice.jpg'),
  },
  {
    id: 'p12',
    title: 'Cà chua beef 1kg',
    shop: 'Koola Fresh Market',
    category: 'grocery',
    price: '45.000đ',
    rating: 4.4,
    soldCount: 740,
    sold: '740',
    delivery: 'Giao 2h',
    accent: '#10B981',
    icon: 'eco',
    tags: ['Organic'],
    description: 'Cà chua beef mọng nước, thịt dày, thích hợp nấu sốt hoặc ăn sống. 1kg khoảng 4-5 trái.',
    seller: { id: 'seller-fresh', name: 'Koola Fresh Market', verified: true, province: 'Đà Lạt' },
    image: require('../../assets/mock-shopping/vegetables.jpg'),
  },
  {
    id: 'p13',
    title: 'Atiso đỏ sấy dẻo 250g',
    shop: 'Koola Fresh Market',
    category: 'grocery',
    price: '65.000đ',
    badge: 'Deal',
    rating: 4.6,
    soldCount: 890,
    sold: '890',
    delivery: 'Freeship',
    accent: '#10B981',
    icon: 'eco',
    tags: ['Không đường', 'Chứng nhận'],
    description: 'Atiso đỏ Đà Lạt sấy dẻo, chua ngọt tự nhiên, không phẩm màu. Hũ 250g.',
    seller: { id: 'seller-fresh', name: 'Koola Fresh Market', verified: true, province: 'Đà Lạt' },
    image: require('../../assets/mock-shopping/chicken-rice.jpg'),
  },
  // ── seller-bep 7 thêm (p14-p20) ──────────────────────────────────
  {
    id: 'p14',
    title: 'Bún bò Huế đặc biệt',
    shop: 'Bếp Nhà Koola',
    category: 'food',
    price: '55.000đ',
    badge: 'Bán chạy',
    rating: 4.8,
    soldCount: 1620,
    sold: '1.6k',
    delivery: '25 phút',
    accent: '#F97316',
    icon: 'restaurant',
    tags: ['Chính hãng', 'Đã xác minh'],
    description: 'Bún bò Huế nước dùng hầm 8 tiếng, thịt bò — chả — huyết đầy đủ. Kèm rau sống và chanh ớt.',
    seller: { id: 'seller-bep', name: 'Bếp Nhà Koola', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/earbuds.jpg'),
  },
  {
    id: 'p15',
    title: 'Gỏi cuốn tôm thịt 10 cuốn',
    shop: 'Bếp Nhà Koola',
    category: 'food',
    price: '49.000đ',
    rating: 4.6,
    soldCount: 1120,
    sold: '1.1k',
    delivery: '25 phút',
    accent: '#F97316',
    icon: 'restaurant',
    tags: ['Không đường'],
    description: 'Gỏi cuốn tôm thịt tươi, bánh tráng mỏng, chấm mắm nêm hoặc tương đậu. Hộp 10 cuốn.',
    seller: { id: 'seller-bep', name: 'Bếp Nhà Koola', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/mop.jpg'),
  },
  {
    id: 'p16',
    title: 'Phở gà ta 1 phần',
    shop: 'Bếp Nhà Koola',
    category: 'food',
    price: '52.000đ',
    badge: 'Hot',
    rating: 4.7,
    soldCount: 980,
    sold: '980',
    delivery: '25 phút',
    accent: '#F97316',
    icon: 'restaurant',
    tags: ['Chính hãng'],
    description: 'Phở gà ta nước trong, thịt gà thả vườn xé, hành ngò thơm. Giao nóng kèm chanh ớt.',
    seller: { id: 'seller-bep', name: 'Bếp Nhà Koola', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/skincare.jpg'),
  },
  {
    id: 'p17',
    title: 'Bánh mì chả cá nóng',
    shop: 'Bếp Nhà Koola',
    category: 'food',
    price: '29.000đ',
    rating: 4.5,
    soldCount: 2500,
    sold: '2.5k',
    delivery: '25 phút',
    accent: '#F97316',
    icon: 'restaurant',
    tags: ['Đã xác minh'],
    description: 'Bánh mì giòn kẹp chả cá Nha Trang chiên nóng, dưa chua và sốt mayo.',
    seller: { id: 'seller-bep', name: 'Bếp Nhà Koola', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/rice.jpg'),
  },
  {
    id: 'p18',
    title: 'Chè khúc bạch 3 màu',
    shop: 'Bếp Nhà Koola',
    category: 'food',
    price: '32.000đ',
    badge: 'Món mới',
    rating: 4.9,
    soldCount: 1340,
    sold: '1.3k',
    delivery: '25 phút',
    accent: '#F97316',
    icon: 'restaurant',
    tags: ['Không đường', 'Chính hãng'],
    description: 'Chè khúc bạch phô mai 3 màu, hạnh nhân lát, nhãn tươi. Ly 350ml, ngọt dịu.',
    seller: { id: 'seller-bep', name: 'Bếp Nhà Koola', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/vegetables.jpg'),
  },
  {
    id: 'p19',
    title: 'Cơm tấm sườn bì chả',
    shop: 'Bếp Nhà Koola',
    category: 'food',
    price: '48.000đ',
    rating: 4.6,
    soldCount: 1560,
    sold: '1.5k',
    delivery: '25 phút',
    accent: '#F97316',
    icon: 'restaurant',
    tags: ['Chính hãng', 'Chứng nhận'],
    description: 'Cơm tấm sườn nướng mật ong, bì thính, chả trứng. Kèm canh chua và nước mắm.',
    seller: { id: 'seller-bep', name: 'Bếp Nhà Koola', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/chicken-rice.jpg'),
  },
  {
    id: 'p20',
    title: 'Trà đào cam sả 700ml',
    shop: 'Bếp Nhà Koola',
    category: 'food',
    price: '35.000đ',
    badge: 'Deal',
    rating: 4.4,
    soldCount: 2100,
    sold: '2.1k',
    delivery: '25 phút',
    accent: '#F97316',
    icon: 'restaurant',
    tags: ['Không đường'],
    description: 'Trà đào cam sả thơm, đào miếng giòn, cam vàng tươi. Ly 700ml đá riêng.',
    seller: { id: 'seller-bep', name: 'Bếp Nhà Koola', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/earbuds.jpg'),
  },
  // ── seller-tech 7 thêm (p21-p27) ─────────────────────────────────
  {
    id: 'p21',
    title: 'Sạc dự phòng 10000mAh',
    shop: 'Tech Corner',
    category: 'electronics',
    price: '289.000đ',
    originalPrice: '399.000đ',
    badge: '-27%',
    rating: 4.7,
    soldCount: 890,
    sold: '890',
    delivery: 'Hôm nay',
    accent: '#2563EB',
    icon: 'battery-charging-full',
    tags: ['Chính hãng', 'Chứng nhận'],
    description: 'Sạc dự phòng 10000mAh sạc nhanh PD 20W, 2 cổng USB-C. Nhỏ gọn, kèm cáp.',
    seller: { id: 'seller-tech', name: 'Tech Corner', verified: false, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/mop.jpg'),
  },
  {
    id: 'p22',
    title: 'Cáp USB-C bện dù 1.5m',
    shop: 'Tech Corner',
    category: 'electronics',
    price: '59.000đ',
    badge: 'Bán chạy',
    rating: 4.8,
    soldCount: 2400,
    sold: '2.4k',
    delivery: 'Hôm nay',
    accent: '#2563EB',
    icon: 'cable',
    tags: ['Chính hãng'],
    description: 'Cáp USB-C bện dù, sạc nhanh 60W, truyền dữ liệu 480Mbps. Dài 1.5m, bền 20k lần gập.',
    seller: { id: 'seller-tech', name: 'Tech Corner', verified: false, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/skincare.jpg'),
  },
  {
    id: 'p23',
    title: 'Giá đỡ điện thoại để bàn',
    shop: 'Tech Corner',
    category: 'electronics',
    price: '79.000đ',
    rating: 4.5,
    soldCount: 760,
    sold: '760',
    delivery: 'Hôm nay',
    accent: '#2563EB',
    icon: 'phone-iphone',
    tags: ['Đã xác minh'],
    description: 'Giá đỡ nhôm để bàn, xoay 360°, gấp gọn. Dùng cho điện thoại và tablet đến 12 inch.',
    seller: { id: 'seller-tech', name: 'Tech Corner', verified: false, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/rice.jpg'),
  },
  {
    id: 'p24',
    title: 'Chuột không dây Silent',
    shop: 'Tech Corner',
    category: 'electronics',
    price: '149.000đ',
    originalPrice: '199.000đ',
    badge: 'Hot',
    rating: 4.6,
    soldCount: 1320,
    sold: '1.3k',
    delivery: 'Hôm nay',
    accent: '#2563EB',
    icon: 'mouse',
    tags: ['Chính hãng', 'Chứng nhận'],
    description: 'Chuột không dây bấm êm, DPI 1600, pin 12 tháng. Kết nối 2.4GHz + Bluetooth.',
    seller: { id: 'seller-tech', name: 'Tech Corner', verified: false, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/vegetables.jpg'),
  },
  {
    id: 'p25',
    title: 'Bàn phím cơ mini 68 phím',
    shop: 'Tech Corner',
    category: 'electronics',
    price: '399.000đ',
    originalPrice: '549.000đ',
    badge: '-27%',
    rating: 4.7,
    soldCount: 430,
    sold: '430',
    delivery: 'Hôm nay',
    accent: '#2563EB',
    icon: 'keyboard',
    tags: ['Chính hãng', 'Đã xác minh'],
    description: 'Bàn phím cơ 68 phím, switch đỏ, LED RGB. Kết nối dây và Bluetooth 5.0.',
    seller: { id: 'seller-tech', name: 'Tech Corner', verified: false, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/chicken-rice.jpg'),
  },
  {
    id: 'p26',
    title: 'Loa Bluetooth mini chống nước',
    shop: 'Tech Corner',
    category: 'electronics',
    price: '199.000đ',
    rating: 4.4,
    soldCount: 680,
    sold: '680',
    delivery: 'Hôm nay',
    accent: '#2563EB',
    icon: 'speaker',
    tags: ['Chính hãng'],
    description: 'Loa Bluetooth 5.3 mini, chống nước IPX5, pin 8h. Âm bass ấm, kẹp ba lô tiện.',
    seller: { id: 'seller-tech', name: 'Tech Corner', verified: false, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/earbuds.jpg'),
  },
  {
    id: 'p27',
    title: 'Ốp lưng trong suốt iPhone',
    shop: 'Tech Corner',
    category: 'electronics',
    price: '49.000đ',
    badge: 'Deal',
    rating: 4.3,
    soldCount: 1800,
    sold: '1.8k',
    delivery: 'Hôm nay',
    accent: '#2563EB',
    icon: 'phone-iphone',
    tags: ['Đã xác minh'],
    description: 'Ốp lưng TPU trong suốt chống ố vàng, viền dày bảo vệ camera. Đủ size iPhone.',
    seller: { id: 'seller-tech', name: 'Tech Corner', verified: false, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/mop.jpg'),
  },
  // ── seller-nhaxinh 7 thêm (p28-p34) ──────────────────────────────
  {
    id: 'p28',
    title: 'Khăn microfiber 3 cái',
    shop: 'Nhà Xinh Store',
    category: 'home',
    price: '45.000đ',
    rating: 4.7,
    soldCount: 1650,
    sold: '1.6k',
    delivery: 'Giao trong ngày',
    accent: '#14B8A6',
    icon: 'home',
    tags: ['Chính hãng'],
    description: 'Khăn microfiber thấm hút, không để lại bụi vải. Set 3 cái 40x40cm, nhiều màu.',
    seller: { id: 'seller-nhaxinh', name: 'Nhà Xinh Store', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/skincare.jpg'),
  },
  {
    id: 'p29',
    title: 'Hộp đựng đồ gấp gọn 45L',
    shop: 'Nhà Xinh Store',
    category: 'home',
    price: '89.000đ',
    originalPrice: '129.000đ',
    badge: '-31%',
    rating: 4.6,
    soldCount: 920,
    sold: '920',
    delivery: 'Giao trong ngày',
    accent: '#14B8A6',
    icon: 'inventory',
    tags: ['Đã xác minh', 'Chính hãng'],
    description: 'Hộp vải đựng đồ gấp gọn 45L, khung thép, nắp đậy. Đựng quần áo, đồ chơi, gọn khi không dùng.',
    seller: { id: 'seller-nhaxinh', name: 'Nhà Xinh Store', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/rice.jpg'),
  },
  {
    id: 'p30',
    title: 'Kệ góc nhà tắm inox',
    shop: 'Nhà Xinh Store',
    category: 'home',
    price: '119.000đ',
    badge: 'Bán chạy',
    rating: 4.5,
    soldCount: 580,
    sold: '580',
    delivery: 'Giao trong ngày',
    accent: '#14B8A6',
    icon: 'shelves',
    tags: ['Chứng nhận', 'Đã xác minh'],
    description: 'Kệ góc inox 304 dán tường không khoan, chịu lực 8kg. 2 tầng, thoát nước nhanh.',
    seller: { id: 'seller-nhaxinh', name: 'Nhà Xinh Store', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/vegetables.jpg'),
  },
  {
    id: 'p31',
    title: 'Thảm chân siêu thấm 40x60',
    shop: 'Nhà Xinh Store',
    category: 'home',
    price: '39.000đ',
    rating: 4.4,
    soldCount: 2100,
    sold: '2.1k',
    delivery: 'Giao trong ngày',
    accent: '#14B8A6',
    icon: 'home',
    tags: ['Chính hãng'],
    description: 'Thảm chân microfiber siêu thấm, đế cao su chống trượt. 40x60cm, giặt máy được.',
    seller: { id: 'seller-nhaxinh', name: 'Nhà Xinh Store', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/chicken-rice.jpg'),
  },
  {
    id: 'p32',
    title: 'Móc dán tường chịu lực 5kg',
    shop: 'Nhà Xinh Store',
    category: 'home',
    price: '29.000đ',
    badge: 'Deal',
    rating: 4.3,
    soldCount: 2400,
    sold: '2.4k',
    delivery: 'Giao trong ngày',
    accent: '#14B8A6',
    icon: 'home',
    tags: ['Đã xác minh'],
    description: 'Móc dán trong suốt chịu lực 5kg, không để lại vết khi tháo. Gói 6 móc.',
    seller: { id: 'seller-nhaxinh', name: 'Nhà Xinh Store', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/earbuds.jpg'),
  },
  {
    id: 'p33',
    title: 'Giỏ đựng đồ giặt có nắp',
    shop: 'Nhà Xinh Store',
    category: 'home',
    price: '99.000đ',
    rating: 4.6,
    soldCount: 720,
    sold: '720',
    delivery: 'Giao trong ngày',
    accent: '#14B8A6',
    icon: 'home',
    tags: ['Chính hãng', 'Chứng nhận'],
    description: 'Giỏ vải đựng đồ giặt 60L có nắp, quai xách, gấp gọn. Vải canvas dày dặn.',
    seller: { id: 'seller-nhaxinh', name: 'Nhà Xinh Store', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/mop.jpg'),
  },
  {
    id: 'p34',
    title: 'Nến thơm soy wax 180g',
    shop: 'Nhà Xinh Store',
    category: 'home',
    price: '85.000đ',
    originalPrice: '109.000đ',
    badge: 'Mới',
    rating: 4.8,
    soldCount: 540,
    sold: '540',
    delivery: 'Giao trong ngày',
    accent: '#14B8A6',
    icon: 'home',
    tags: ['Organic', 'Chính hãng'],
    description: 'Nến thơm sáp đậu nành 180g, hương gỗ đàn, cháy 35h. Hũ thủy tinh tái dùng.',
    seller: { id: 'seller-nhaxinh', name: 'Nhà Xinh Store', verified: true, province: 'TP.HCM' },
    image: require('../../assets/mock-shopping/skincare.jpg'),
  },
  // ── seller-beauty 7 thêm (p35-p41) ───────────────────────────────
  {
    id: 'p35',
    title: 'Son tint lì 5 màu',
    shop: 'Beauty Lab',
    category: 'beauty',
    price: '89.000đ',
    originalPrice: '119.000đ',
    badge: 'Hot',
    rating: 4.8,
    soldCount: 1850,
    sold: '1.8k',
    delivery: 'Freeship',
    accent: '#EC4899',
    icon: 'spa',
    tags: ['Chính hãng', 'Chứng nhận'],
    description: 'Son tint lì mịn môi, giữ màu 8h, 5 tông MLBB. Không khô môi, mùi trái cây nhẹ.',
    seller: { id: 'seller-beauty', name: 'Beauty Lab', verified: true, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/rice.jpg'),
  },
  {
    id: 'p36',
    title: 'Mặt nạ đất sét 100ml',
    shop: 'Beauty Lab',
    category: 'beauty',
    price: '95.000đ',
    rating: 4.7,
    soldCount: 1320,
    sold: '1.3k',
    delivery: 'Freeship',
    accent: '#EC4899',
    icon: 'spa',
    tags: ['Chính hãng'],
    description: 'Mặt nạ đất sét kiềm dầu, thu nhỏ lỗ chân lông. Tuýp 100ml, dùng 2 lần/tuần.',
    seller: { id: 'seller-beauty', name: 'Beauty Lab', verified: true, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/vegetables.jpg'),
  },
  {
    id: 'p37',
    title: 'Kem chống nắng SPF50 50ml',
    shop: 'Beauty Lab',
    category: 'beauty',
    price: '159.000đ',
    badge: 'Bán chạy',
    rating: 4.9,
    soldCount: 2200,
    sold: '2.2k',
    delivery: 'Freeship',
    accent: '#EC4899',
    icon: 'spa',
    tags: ['Chính hãng', 'Đã xác minh'],
    description: 'Kem chống nắng SPF50 PA++++, không bết dính, nâng tone nhẹ. 50ml.',
    seller: { id: 'seller-beauty', name: 'Beauty Lab', verified: true, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/chicken-rice.jpg'),
  },
  {
    id: 'p38',
    title: 'Toner hoa hồng 200ml',
    shop: 'Beauty Lab',
    category: 'beauty',
    price: '109.000đ',
    originalPrice: '139.000đ',
    badge: '-21%',
    rating: 4.6,
    soldCount: 890,
    sold: '890',
    delivery: 'Freeship',
    accent: '#EC4899',
    icon: 'spa',
    tags: ['Organic', 'Chính hãng'],
    description: 'Toner hoa hồng cấp ẩm, cân bằng pH, không cồn. Chai 200ml.',
    seller: { id: 'seller-beauty', name: 'Beauty Lab', verified: true, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/earbuds.jpg'),
  },
  {
    id: 'p39',
    title: 'Dầu gội bưởi 300ml',
    shop: 'Beauty Lab',
    category: 'beauty',
    price: '119.000đ',
    rating: 4.5,
    soldCount: 760,
    sold: '760',
    delivery: 'Freeship',
    accent: '#EC4899',
    icon: 'spa',
    tags: ['Organic'],
    description: 'Dầu gội tinh dầu bưởi kích mọc tóc, giảm gãy rụng. Chai 300ml.',
    seller: { id: 'seller-beauty', name: 'Beauty Lab', verified: true, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/mop.jpg'),
  },
  {
    id: 'p40',
    title: 'Kem dưỡng ẩm 50g',
    shop: 'Beauty Lab',
    category: 'beauty',
    price: '139.000đ',
    badge: 'Deal',
    rating: 4.7,
    soldCount: 1450,
    sold: '1.4k',
    delivery: 'Freeship',
    accent: '#EC4899',
    icon: 'spa',
    tags: ['Chính hãng', 'Chứng nhận'],
    description: 'Kem dưỡng ẩm ceramide, phục hồi hàng rào da. Hũ 50g, thấm nhanh không nhờn.',
    seller: { id: 'seller-beauty', name: 'Beauty Lab', verified: true, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/skincare.jpg'),
  },
  {
    id: 'p41',
    title: 'Tẩy trang micellar 400ml',
    shop: 'Beauty Lab',
    category: 'beauty',
    price: '99.000đ',
    originalPrice: '129.000đ',
    badge: '-23%',
    rating: 4.8,
    soldCount: 1900,
    sold: '1.9k',
    delivery: 'Freeship',
    accent: '#EC4899',
    icon: 'spa',
    tags: ['Chính hãng', 'Đã xác minh'],
    description: 'Nước tẩy trang micellar 3-in-1, sạch sâu không cần rửa lại. Chai 400ml.',
    seller: { id: 'seller-beauty', name: 'Beauty Lab', verified: true, province: 'Hà Nội' },
    image: require('../../assets/mock-shopping/rice.jpg'),
  },
  // ── seller-choviet 7 thêm (p42-p48) ──────────────────────────────
  {
    id: 'p42',
    title: 'Nước mắm truyền thống 500ml',
    shop: 'Chợ Việt Online',
    category: 'grocery',
    price: '55.000đ',
    rating: 4.7,
    soldCount: 1240,
    sold: '1.2k',
    delivery: 'Giao 4h',
    accent: '#F59E0B',
    icon: 'rice-bowl',
    tags: ['Đã xác minh', 'Chính hãng'],
    description: 'Nước mắm nhĩ Phú Quốc 40 độ đạm, ủ chượp 12 tháng. Chai thủy tinh 500ml.',
    seller: { id: 'seller-choviet', name: 'Chợ Việt Online', verified: false, province: 'Cần Thơ' },
    image: require('../../assets/mock-shopping/vegetables.jpg'),
  },
  {
    id: 'p43',
    title: 'Bún gạo khô 1kg',
    shop: 'Chợ Việt Online',
    category: 'grocery',
    price: '39.000đ',
    badge: 'Bán chạy',
    rating: 4.6,
    soldCount: 1680,
    sold: '1.6k',
    delivery: 'Giao 4h',
    accent: '#F59E0B',
    icon: 'rice-bowl',
    tags: ['Organic'],
    description: 'Bún gạo khô sợi nhỏ, dai không nát. Gói 1kg, nấu bún xào hay bún nước đều ngon.',
    seller: { id: 'seller-choviet', name: 'Chợ Việt Online', verified: false, province: 'Cần Thơ' },
    image: require('../../assets/mock-shopping/chicken-rice.jpg'),
  },
  {
    id: 'p44',
    title: 'Dầu ăn gạo lứt 1L',
    shop: 'Chợ Việt Online',
    category: 'grocery',
    price: '62.000đ',
    originalPrice: '79.000đ',
    badge: '-21%',
    rating: 4.5,
    soldCount: 890,
    sold: '890',
    delivery: 'Giao 4h',
    accent: '#F59E0B',
    icon: 'rice-bowl',
    tags: ['Chứng nhận', 'Chính hãng'],
    description: 'Dầu gạo lứt nguyên chất, giàu gamma oryzanol. Chai 1L, chiên xào thơm nhẹ.',
    seller: { id: 'seller-choviet', name: 'Chợ Việt Online', verified: false, province: 'Cần Thơ' },
    image: require('../../assets/mock-shopping/earbuds.jpg'),
  },
  {
    id: 'p45',
    title: 'Mắm ruốc Huế hũ 400g',
    shop: 'Chợ Việt Online',
    category: 'grocery',
    price: '48.000đ',
    rating: 4.8,
    soldCount: 720,
    sold: '720',
    delivery: 'Giao 4h',
    accent: '#F59E0B',
    icon: 'rice-bowl',
    tags: ['Đã xác minh'],
    description: 'Mắm ruốc Huế thơm đậm, chấm rau luộc hay nấu bún bò đều ngon. Hũ 400g.',
    seller: { id: 'seller-choviet', name: 'Chợ Việt Online', verified: false, province: 'Cần Thơ' },
    image: require('../../assets/mock-shopping/mop.jpg'),
  },
  {
    id: 'p46',
    title: 'Đường thốt nốt 1kg',
    shop: 'Chợ Việt Online',
    category: 'grocery',
    price: '42.000đ',
    badge: 'Deal',
    rating: 4.4,
    soldCount: 1120,
    sold: '1.1k',
    delivery: 'Giao 4h',
    accent: '#F59E0B',
    icon: 'rice-bowl',
    tags: ['Organic', 'Đã xác minh'],
    description: 'Đường thốt nốt An Giang nguyên chất, ngọt thanh, nấu chè hay pha nước đều ngon. Gói 1kg.',
    seller: { id: 'seller-choviet', name: 'Chợ Việt Online', verified: false, province: 'Cần Thơ' },
    image: require('../../assets/mock-shopping/skincare.jpg'),
  },
  {
    id: 'p47',
    title: 'Khô cá lóc 500g',
    shop: 'Chợ Việt Online',
    category: 'grocery',
    price: '89.000đ',
    originalPrice: '109.000đ',
    badge: 'Hot',
    rating: 4.6,
    soldCount: 540,
    sold: '540',
    delivery: 'Giao 4h',
    accent: '#F59E0B',
    icon: 'rice-bowl',
    tags: ['Đã xác minh', 'Chứng nhận'],
    description: 'Khô cá lóc đồng, ướp muối ớt vừa ăn, phơi nắng tự nhiên. Gói 500g hút chân không.',
    seller: { id: 'seller-choviet', name: 'Chợ Việt Online', verified: false, province: 'Cần Thơ' },
    image: require('../../assets/mock-shopping/rice.jpg'),
  },
  {
    id: 'p48',
    title: 'Hạt điều rang muối 300g',
    shop: 'Chợ Việt Online',
    category: 'grocery',
    price: '75.000đ',
    rating: 4.9,
    soldCount: 1560,
    sold: '1.5k',
    delivery: 'Giao 4h',
    accent: '#F59E0B',
    icon: 'rice-bowl',
    tags: ['Chính hãng'],
    description: 'Hạt điều Bình Phước rang muối giòn bùi, hạt to đều. Hũ 300g.',
    seller: { id: 'seller-choviet', name: 'Chợ Việt Online', verified: false, province: 'Cần Thơ' },
    image: require('../../assets/mock-shopping/vegetables.jpg'),
  },
];
